name: test_reflectable
description: >
  This package contains tests which depend on package reflectable
  and which are transformed by the transformer in that package.
version: 1.0.2-draf.1
author: The Dart Team <dart@google.com>
homepage: https://www.github.com/dart-lang/reflectable
dependencies:
  reflectable:
    path: ../reflectable
dev_dependencies:
  unittest: ^0.11.0
transformers:
- reflectable:
    entry_points: ["test/*_test.dart"]
    formatted: true
- $dart2js:
    $include: []
